// <auto-generated />
using System;
using Agaval.Inventory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agaval.Inventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PersistenceContext))]
    partial class PersistenceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Agaval.Inventory.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id")
                        .HasName("PK_Categorias");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Categorias_Nombre");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Electrónica"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Oficina"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Aseo"
                        });
                });

            modelBuilder.Entity("Agaval.Inventory.Domain.Entities.InventoryMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Observation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Observacion");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductoId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TipoMovimiento");

                    b.HasKey("Id")
                        .HasName("PK_MovimientosInventario");

                    b.HasIndex("ProductId", "OccurredAt")
                        .HasDatabaseName("IX_Movimientos_ProductoId_Fecha");

                    b.ToTable("MovimientosInventario", null, t =>
                        {
                            t.HasCheckConstraint("CK_Movimientos_Cantidad", "[Cantidad] > 0");

                            t.HasCheckConstraint("CK_Movimientos_Tipo", "[TipoMovimiento] IN ('ENTRADA', 'SALIDA')");
                        });
                });

            modelBuilder.Entity("Agaval.Inventory.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<int>("MinimumStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5)
                        .HasColumnName("StockMinimo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Precio");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Stock");

                    b.HasKey("Id")
                        .HasName("PK_Productos");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Productos_CategoriaId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Productos_FechaCreacion");

                    b.ToTable("Productos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Productos_Precio", "[Precio] > 0");

                            t.HasCheckConstraint("CK_Productos_Stock", "[Stock] >= 0");

                            t.HasCheckConstraint("CK_Productos_StockMinimo", "[StockMinimo] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 8, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Teclado compacto para estaciones de trabajo.",
                            MinimumStock = 5,
                            Name = "Teclado mecánico",
                            Price = 249900m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 8, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Papel blanco de 75 gramos, paquete de 500 hojas.",
                            MinimumStock = 8,
                            Name = "Resma de papel carta",
                            Price = 24500m,
                            Stock = 18
                        });
                });

            modelBuilder.Entity("Agaval.Inventory.Domain.Entities.InventoryMovement", b =>
                {
                    b.HasOne("Agaval.Inventory.Domain.Entities.Product", "Product")
                        .WithMany("Movements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Movimientos_Productos");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Agaval.Inventory.Domain.Entities.Product", b =>
                {
                    b.HasOne("Agaval.Inventory.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Productos_Categorias");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Agaval.Inventory.Domain.Entities.Product", b =>
                {
                    b.Navigation("Movements");
                });
#pragma warning restore 612, 618
        }
    }
}
