@AgavalInventoryApi = http://localhost:5100
@token = PEGAR_ACCESS_TOKEN_DEL_LOGIN

GET {{AgavalInventoryApi}}/health
Accept: application/json

###

GET {{AgavalInventoryApi}}/api/categorias
Authorization: Bearer {{token}}
Accept: application/json

###

POST {{AgavalInventoryApi}}/api/autenticacion/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Agaval_admin_2026!"
}

###

GET {{AgavalInventoryApi}}/api/productos?stock=All&buscar=&pagina=1&tamanoPagina=10&ordenarPor=Name&direccion=Ascending
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{AgavalInventoryApi}}/api/productos/resumen
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{AgavalInventoryApi}}/api/movimientos-inventario?pagina=1&tamanoPagina=10
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{AgavalInventoryApi}}/api/categorias?incluirInactivas=true
Authorization: Bearer {{token}}
Accept: application/json

###

POST {{AgavalInventoryApi}}/api/categorias
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Ferretería"
}

###

POST {{AgavalInventoryApi}}/api/productos
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Mouse ergonómico",
  "description": "Mouse vertical inalámbrico",
  "price": 129900,
  "stock": 6,
  "minimumStock": 4,
  "categoryId": 1
}

###

POST {{AgavalInventoryApi}}/api/productos/1/ajustes-stock
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "type": "Entry",
  "quantity": 5,
  "observation": "Recepción de proveedor"
}
