apiVersion: v1
kind: Secret
metadata:
  name: agaval-secrets
type: Opaque
stringData:
  database-connection: Host=aws-0-REGION.pooler.supabase.com;Port=5432;Database=postgres;Username=postgres.PROJECT_REF;Password=CHANGE_ME;SSL Mode=Require;Trust Server Certificate=true
