CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822153207_InitialCreate') THEN
    CREATE TABLE "Categorias" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(100) NOT NULL,
        "Activo" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_Categorias" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822153207_InitialCreate') THEN
    CREATE TABLE "Productos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(150) NOT NULL,
        "Descripcion" character varying(500),
        "Precio" numeric(10,2) NOT NULL,
        "Stock" integer NOT NULL DEFAULT 0,
        "StockMinimo" integer NOT NULL DEFAULT 5,
        "CategoriaId" integer NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Productos" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Productos_Precio" CHECK ("Precio" > 0),
        CONSTRAINT "CK_Productos_Stock" CHECK ("Stock" >= 0),
        CONSTRAINT "CK_Productos_StockMinimo" CHECK ("StockMinimo" >= 0),
        CONSTRAINT "FK_Productos_Categorias" FOREIGN KEY ("CategoriaId") REFERENCES "Categorias" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822153207_InitialCreate') THEN
    CREATE TABLE "MovimientosInventario" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductoId" integer NOT NULL,
        "TipoMovimiento" character varying(10) NOT NULL,
        "Cantidad" integer NOT NULL,
        "Fecha" timestamp with time zone NOT NULL,
        "Observacion" character varying(255),
        CONSTRAINT "PK_MovimientosInventario" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Movimientos_Cantidad" CHECK ("Cantidad" > 0),
        CONSTRAINT "CK_Movimientos_Tipo" CHECK ("TipoMovimiento" IN ('ENTRADA', 'SALIDA')),
        CONSTRAINT "FK_Movimientos_Productos" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822153207_InitialCreate') THEN
    INSERT INTO "Categorias" ("Id", "Activo", "Nombre")
    VALUES (1, TRUE, 'Electrónica');
    INSERT INTO "Categorias" ("Id", "Activo", "Nombre")
    VALUES (2, TRUE, 'Oficina');
    INSERT INTO "Categorias" ("Id", "Activo", "Nombre")
    VALUES (3, TRUE, 'Aseo');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822153207_InitialCreate') THEN
    INSERT INTO "Productos" ("Id", "CategoriaId", "FechaCreacion", "Descripcion", "StockMinimo", "Nombre", "Precio", "Stock")
    VALUES (1, 1, TIMESTAMPTZ '2026-08-01T12:00:00+00:00', 'Teclado compacto para estaciones de trabajo.', 5, 'Teclado mecánico', 249900.0, 4);
    INSERT INTO "Productos" ("Id", "CategoriaId", "FechaCreacion", "Descripcion", "StockMinimo", "Nombre", "Precio", "Stock")
    VALUES (2, 2, TIMESTAMPTZ '2026-08-01T12:00:00+00:00', 'Papel blanco de 75 gramos, paquete de 500 hojas.', 8, 'Resma de papel carta', 24500.0, 18);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822153207_InitialCreate') THEN
    CREATE UNIQUE INDEX "UX_Categorias_Nombre" ON "Categorias" ("Nombre");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822153207_InitialCreate') THEN
    CREATE INDEX "IX_Movimientos_ProductoId_Fecha" ON "MovimientosInventario" ("ProductoId", "Fecha");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822153207_InitialCreate') THEN
    CREATE INDEX "IX_Productos_CategoriaId" ON "Productos" ("CategoriaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822153207_InitialCreate') THEN
    CREATE INDEX "IX_Productos_FechaCreacion" ON "Productos" ("FechaCreacion");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822153207_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Categorias"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Categorias") + 1,
            nextval(pg_get_serial_sequence('"Categorias"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Productos"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Productos") + 1,
            nextval(pg_get_serial_sequence('"Productos"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822153207_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260822153207_InitialCreate', '10.0.11');
    END IF;
END $EF$;
COMMIT;

